In [183]:
import glob
import numpy as np

In [184]:
permutationFiles =  glob.glob(".\\data\\ntsb[0-9]*.txt-1-5-5-0-out.perm-*")
len(permutationFiles)

2100

In [185]:
permutationData = []
for file in permutationFiles:
    with open(file) as f:
        permutationData.append(f.readlines())

In [186]:
mn = 30000
mx = 0
lens = []
for data in permutationData:
    mn = min(mn, len(data))
    mx = max(mx, len(data))
    lens.append(len(data))
    
print(np.percentile(lens, 90))
print(mn)
print(mx)

15.100000000000136
6
19


In [203]:
num_files = len(permutationData)
max_seq_len = 10
processedData = np.array([[" " for i in range(max_seq_len)] for i in range(num_files)], dtype = object)
processedDataPerm = np.array([[-1 for i in range(max_seq_len)] for i in range(num_files)])
for i in range(num_files):
    fileData = permutationData[i]
    j = 0
    for line in fileData:
        processedData[i][j] = ' '.join(line.split(' ')[1:]).strip()
        
        if(int(line.split(' ')[0].split('-')[-1]) <= max_seq_len):
            processedDataPerm[i][j] = int(line.split(' ')[0].split('-')[-1]) - 1
            j += 1
        if( j >= max_seq_len ):
            break
        
        

In [204]:
with open('.\\data\\processed\\sentences.txt','w') as f:
    for line in processedData:
        f.write('\t'.join(line).strip() + '\n')

In [205]:
with open('.\\data\\processed\\permutations.txt','w') as f:
    for line in processedDataPerm:
        f.write('\t'.join(line.astype(str)).strip() + '\n')

In [136]:
with open('.\\data\\processed\\sentences.txt') as f:
    sentences = f.readlines()

X = []
for line in sentences:
    xx = [[" "] for i in range(max_seq_len)]
    lineSents = line.split('\t')
    j = 0
    for ls in lineSents:
        xx[j][0] = ls
        j += 1
    X.append(xx)
    
X = np.asarray(X)


In [138]:
X

array([[['This is preliminary information, subject to change, and may contain errors.'],
        ['Any errors in this report will be corrected when the final report has been completed.'],
        ['On January 13, 1994, about 1230 hours Greenwich Mean Time, a Beech BE-90, N46WA, registered to Charles Kuykendall, Wilmer, Texas, was destroyed during a ditching in international waters about 50 nautical miles south of Martigues, France.'],
        ...,
        ['According to Hungarian records, the airplane was substantially damaged in a previous accident on March 9, 1991.'],
        ['The airplane remained in Hungary until it was purchased by the current registrant.\n'],
        [' ']],

       [['After the ditching, the pilot utilized survival equipment and was later rescued by a search and rescue helicopter.'],
        ['According to the pilot, an electrical fire started and produced smoke in the cockpit during the flight from Straubling-Wallmuhl, Germany, to the Azores, Portugal.'],
    

In [169]:
from keras.utils.np_utils import to_categorical
YY = []
for y_ in y:
    yy = []
    dummyVec = np.array([ 0 for i in range(15)])
    for yy_ in y_:
        if( yy_ != -1):
            dummyVec[yy_] = 1
        yy.append(np.copy(dummyVec))
        dummyVec[yy_] = 0
    YY.append(yy)
    
YY = np.asarray(YY)
YY.shape

(2100, 15, 15)

In [170]:
# YY = []
# for y_ in y:
#     print(to_categorical(y_).shape)
    
YY2 = to_categorical(y)    
YY2.shape

(2100, 15, 15)

In [171]:
np.all(YY == YY2)

False

In [172]:
YY2[0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [181]:
YY[22]

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [180]:
y[22]

array([ 7, 10,  1,  6,  5,  4,  9,  2,  8,  3,  0, -1, -1, -1, -1])

In [182]:
from UniversalEmbeddingModels import *

model = PointerLstmBased(15)
model.summary()

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sent_inp (InputLayer)        (None, 15, 1)             0         
_________________________________________________________________
time_distributed_1 (TimeDist (None, 15, 512)           0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 15, 100)           245200    
_________________________________________________________________
pointer_lstm_1 (PointerLSTM) (None, 15, 15)            60300     
Total params: 305,500
Trainable params: 305,500
Non-trainable params: 0
_________________________________________________________________
